[package]
name = "rust-proxy"
version = "0.1.0"
edition = "2021"
description = ""
repository = ""
readme = "README.MD"
license = "MIT OR Apache-2.0"
keywords = []

[[bin]]
name = "rust-proxy"
path = "src/main.rs"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
tower = "0.5.2"
chrono = "0.4.40"

[dev-dependencies]
httpmock = "0.7.0"
